// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEN5fHNeISU3xqNGH6cDjkRjrbQF_Qi2s',
    appId: '1:376768309216:web:3480056ded914c68f6ad85',
    messagingSenderId: '376768309216',
    projectId: 'e-shop-407ac',
    authDomain: 'e-shop-407ac.firebaseapp.com',
    storageBucket: 'e-shop-407ac.firebasestorage.app',
    measurementId: 'G-T5CH6E2906',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABgZStg3ZSDXJ7UdjKFVTEYH0Xg8aox6M',
    appId: '1:376768309216:android:222f8d8be36ab5dcf6ad85',
    messagingSenderId: '376768309216',
    projectId: 'e-shop-407ac',
    storageBucket: 'e-shop-407ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCis5nmBLG329q6QtzIEHcJO1mBMnCe_pA',
    appId: '1:376768309216:ios:2222196a7a479b19f6ad85',
    messagingSenderId: '376768309216',
    projectId: 'e-shop-407ac',
    storageBucket: 'e-shop-407ac.firebasestorage.app',
    iosBundleId: 'com.example.eShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCis5nmBLG329q6QtzIEHcJO1mBMnCe_pA',
    appId: '1:376768309216:ios:2222196a7a479b19f6ad85',
    messagingSenderId: '376768309216',
    projectId: 'e-shop-407ac',
    storageBucket: 'e-shop-407ac.firebasestorage.app',
    iosBundleId: 'com.example.eShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEN5fHNeISU3xqNGH6cDjkRjrbQF_Qi2s',
    appId: '1:376768309216:web:93d308c7782d4945f6ad85',
    messagingSenderId: '376768309216',
    projectId: 'e-shop-407ac',
    authDomain: 'e-shop-407ac.firebaseapp.com',
    storageBucket: 'e-shop-407ac.firebasestorage.app',
    measurementId: 'G-SW5B65MVN2',
  );
}
